export const data = {  
   "id":"demo@0.1.0",
   "nodes":{  
      "1":{  
         "id":1,
         "data":{  
            "num":2
         },
         "inputs":{  

         },
         "outputs":{  
            "num":{  
               "connections":[  
                  {  
                     "node":3,
                     "input":"num1",
                     "data":{  

                     }
                  }
               ]
            }
         },
         "position":[  
            80,
            250
         ],
         "name":"Number"
      },
      "2":{  
         "id":2,
         "data":{  
            "num":3
         },
         "inputs":{  

         },
         "outputs":{  
            "num":{  
               "connections":[  
                  {  
                     "node":3,
                     "input":"num2",
                     "data":{  

                     }
                  }
               ]
            }
         },
         "position":[  
            80,
            400
         ],
         "name":"Number"
      },
      "3":{  
         "id":3,
         "data":{  
            "num1":0,
            "num2":0,
            "preview":0
         },
         "inputs":{  
            "num1":{  
               "connections":[  
                  {  
                     "node":1,
                     "output":"num",
                     "data":{  

                     }
                  }
               ]
            },
            "num2":{  
               "connections":[  
                  {  
                     "node":2,
                     "output":"num",
                     "data":{  

                     }
                  }
               ]
            }
         },
         "outputs":{  
            "num":{  
               "connections":[  

               ]
            }
         },
         "position":[  
            500,
            240
         ],
         "name":"Add"
      },
      "4":{  
         "id":4,
         "data":{  
            "num1":0,
            "num2":0,
            "preview":0
         },
         "inputs":{  
            "num1":{  
               "connections":[  
                  {  
                     "node":1,
                     "output":"num",
                     "data":{  

                     }
                  }
               ]
            },
            "num2":{  
               "connections":[  
                  {  
                     "node":2,
                     "output":"num",
                     "data":{  

                     }
                  }
               ]
            }
         },
         "outputs":{  
            "num":{  
               "connections":[  

               ]
            }
         },
         "position":[  
            700,
            240
         ],
         "name":"Add"
      },
      "5":{  
         "id":5,
         "data":{  
            "num":4
         },
         "inputs":{  

         },
         "outputs":{  
            "num":{  
               "connections":[  
                  {  
                     "node":3,
                     "input":"num3",
                     "data":{  

                     }
                  }
               ]
            }
         },
         "position":[  
            80,
            100
         ],
         "name":"Number"
      },
   }
}